//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ground
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ground()
        {
            this.tbl_GroundBooking = new HashSet<tbl_GroundBooking>();
        }
    
        public int GroundId { get; set; }
        public string GroundName { get; set; }
        public string GroundDesc { get; set; }
        public string GroundAddress { get; set; }
        public string GroundManager { get; set; }
        public Nullable<int> GroundContact { get; set; }
        public byte[] GroundImage { get; set; }
        public string IsApproved { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string GroundCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroundBooking> tbl_GroundBooking { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_Ground tbl_Ground1 { get; set; }
        public virtual tbl_Ground tbl_Ground2 { get; set; }
        public virtual tbl_Location tbl_Location { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
